id: P85DF25B8
initial_creation_type: ocr
source_metadata:
  volumes:
    0ee937ce4538476399662b8e6e813d72:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: སྒྲོལ་མའི་རྟོག་པ་ལས་འབྱུང་བའི་ཚིག་ལྷུག་པའི་རིགས་བྱེད་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      volume_number: 40
